<Project Sdk="Microsoft.NET.Sdk" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<Import Project="KSADLLs.props" />
	<PropertyGroup>
		<ModName>KittenExtensions</ModName>
		<Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
		<Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
		<TargetFramework>net10.0</TargetFramework>
		<TargetFrameworkVersion>net10.0</TargetFrameworkVersion>
		<LanguageTargets>$(MSBuildToolsPath)\Microsoft.CSharp.targets</LanguageTargets>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<LangVersion>14.0</LangVersion>
		<OutputPath>bin\$(Configuration)</OutputPath>
		<AssemblyName>$(ModName)</AssemblyName>
		<OutputType>Library</OutputType>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>

		<VersionPrefix>0.5.1</VersionPrefix>
		<Version>$(VersionPrefix)</Version>
		<AssemblyVersion>0.5.0.0</AssemblyVersion>
		<FileVersion>$(VersionPrefix).0</FileVersion>

		<GitShortHash>nogit</GitShortHash>
		<InformationalVersionPostfix></InformationalVersionPostfix>
		<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>

		<Authors>tom_is_unlucky, AMPW</Authors>
		<Description>XML Patching (ModuleManager like), Custom XML Assets</Description>
		<Copyright>MIT</Copyright>
	</PropertyGroup>

	<PropertyGroup>
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<Optimize>false</Optimize>
		<DefineConstants>TRACE</DefineConstants>
		<ErrorReport>prompt</ErrorReport>
		<WarningLevel>4</WarningLevel>
		<Prefer32Bit>false</Prefer32Bit>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<DefineConstants>$(DefineConstants);DEBUG</DefineConstants>
		<InformationalVersionPostfix>-debug</InformationalVersionPostfix>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<Optimize>true</Optimize>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../XPathPatch/XPathPatch.csproj" />

		<PackageReference Include="Lib.Harmony" Version="2.4.2" />
		<Reference Include="StarMap.API">
			<HintPath>$(KSAModsDir)StarMap/StarMap.API.dll</HintPath>
			<Private>False</Private>
		</Reference>
	</ItemGroup>

	<Target Name="SetVersionMetadata" BeforeTargets="GetAssemblyVersion">
		<Exec Command="git rev-parse --short HEAD" ConsoleToMSBuild="true" IgnoreExitCode="true"
			IgnoreStandardErrorWarningFormat="true">
			<Output TaskParameter="ConsoleOutput" PropertyName="GitShortHashRaw" />
		</Exec>

		<PropertyGroup>
			<GitShortHash Condition="'$(GitShortHashRaw)' != ''">
				$([System.String]::Copy('$(GitShortHashRaw)').Trim())</GitShortHash>
			<GitShortHash Condition="'$(GitShortHash)' == ''">nogit</GitShortHash>
			<InformationalVersion>v$(VersionPrefix).$(GitShortHash)$(InformationalVersionPostfix)</InformationalVersion>
			<ProductVersion>$(InformationalVersion)</ProductVersion>
		</PropertyGroup>
	</Target>

	<Import Project="CopyOutput.targets" />
</Project>